# Generated by Django 6.0.2 on 2026-04-25 09:15

import shipments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(default=shipments.models.generate_tracking_number, max_length=20, unique=True)),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_phone', models.CharField(max_length=20)),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_phone', models.CharField(max_length=20)),
                ('pickup_address', models.TextField()),
                ('delivery_address', models.TextField()),
                ('parcel_size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra Large', 'Extra Large')], max_length=20)),
                ('parcel_weight', models.DecimalField(decimal_places=2, help_text='Weight in KG', max_digits=6)),
                ('delivery_option', models.CharField(choices=[('Standard', 'Standard Delivery'), ('Next Day', 'Next Day Delivery'), ('Same Day', 'Same Day Delivery')], max_length=20)),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('Collected', 'Collected'), ('In Transit', 'In Transit'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Booked', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
